name: Compile
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: |
        git submodule update
    - name: Make
      run: make
